# Generated by Django 4.1.13 on 2024-05-30 01:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dr", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RolePlayingRoom",
        ),
    ]
