# Generated by Django 4.1.13 on 2024-05-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dr", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="RolePlayingRoom",
        ),
    ]
