# Generated by Django 4.1.13 on 2024-05-31 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dr", "0005_roleplayingroom"),
    ]

    operations = [
        migrations.CreateModel(
            name="SleepClinicRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("situation", models.CharField(max_length=100, verbose_name="상황")),
                (
                    "situation_kr",
                    models.CharField(
                        blank=True,
                        help_text="GPT 프롬프트에 직접적으로 활용됩니다. 비워두시면, situation 필드를 번역하여 자동 반영됩니다.",
                        max_length=100,
                        verbose_name="상황 (한국어)",
                    ),
                ),
                (
                    "my_role",
                    models.CharField(default="환자", max_length=100, verbose_name="내 역할"),
                ),
                (
                    "gpt_role",
                    models.CharField(
                        default="수면클리닉 의사", max_length=100, verbose_name="GPT 역할"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-pk"],
            },
        ),
        migrations.DeleteModel(
            name="RolePlayingRoom",
        ),
    ]
