# Generated by Django 5.0.2 on 2024-06-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0006_sleepclinicroom_delete_roleplayingroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepclinicroom',
            name='situation',
            field=models.CharField(default='기본 상황', max_length=100, verbose_name='상황'),
        ),
    ]
