# Generated by Django 4.1.13 on 2024-05-31 00:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="short_description",
        ),
    ]
