# Generated by Django 4.2.13 on 2024-06-03 03:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_image",
        ),
        migrations.RemoveField(
            model_name="user",
            name="short_description",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
