version: '3.9'

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 final.asgi:application
# gunicorn final.wsgi:application --bind 0.0.0.0:8000     

    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=eunoianest_db_user
      - POSTGRES_PASSWORD=eunoianest
      - POSTGRES_DB=eunoia_dev

  redis:
    image: "redis:latest"
    ports:       - "6397:6397"

volumes:
  postgres_data:
