version: '3.9'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app_static
      - media_volume:/usr/src/app_media
    ports:
      - 80:80
    depends_on:
      - web

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 final.asgi:application
# gunicorn final.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/_static
      - media_volume:/usr/src/app/_media
      - ./:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  static_volume:
  media_volume:
