# Generated by Django 5.0.2 on 2024-06-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_post_hook_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
