# Generated by Django 4.2.13 on 2024-06-03 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="votes",
        ),
        migrations.RemoveField(
            model_name="question",
            name="pub_date",
        ),
        migrations.RemoveField(
            model_name="question",
            name="texts",
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("choice", "Choice"),
                    ("multiple", "Multiple"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="text",
            field=models.TextField(default=1, help_text="Enter the question text."),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="survey.question",
            ),
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_response", models.TextField(blank=True, null=True)),
                ("user_id", models.IntegerField()),
                (
                    "choice_responses",
                    models.ManyToManyField(blank=True, to="survey.choice"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey.question",
                    ),
                ),
            ],
        ),
    ]
