# Generated by Django 4.1.13 on 2024-06-10 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("survey", "0004_message_surveyroom_delete_question_delete_response"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pred",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("predict", models.TextField(max_length=1, verbose_name="결과")),
                ("survey1", models.TextField(max_length=1, verbose_name="숙면여부")),
                ("survey2", models.TextField(max_length=1, verbose_name="스트레스의 강도")),
                ("survey3", models.TextField(max_length=1, verbose_name="긴장의 강도")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="일자")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
        ),
    ]
