# Generated by Django 4.1.13 on 2024-06-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0006_alter_pred_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pred",
            name="user",
            field=models.CharField(max_length=255),
        ),
    ]
