# Generated by Django 4.1.13 on 2024-06-10 05:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0007_alter_pred_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pred",
            old_name="created",
            new_name="date",
        ),
    ]
