# Generated by Django 4.1.13 on 2024-06-10 06:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0010_pred"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pred",
        ),
    ]
