# Generated by Django 4.1.13 on 2024-06-11 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0015_alter_pred_positive_survey_alter_pred_predict_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pluspred",
            name="date",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                unique=True,
                verbose_name="일자",
            ),
            preserve_default=False,
        ),
    ]
