# Generated by Django 4.1.13 on 2024-06-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0016_pluspred_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pluspred",
            name="alcohol_survey",
            field=models.SmallIntegerField(verbose_name="알코올의 강도"),
        ),
        migrations.AlterField(
            model_name="pluspred",
            name="caffeine_survey",
            field=models.SmallIntegerField(verbose_name="카페인 강도"),
        ),
        migrations.AlterField(
            model_name="pluspred",
            name="dream_survey",
            field=models.SmallIntegerField(verbose_name="꿈의 강도"),
        ),
        migrations.AlterField(
            model_name="pluspred",
            name="home_survey",
            field=models.SmallIntegerField(verbose_name="집에서 많은 시간을 보내는지의 여부"),
        ),
        migrations.AlterField(
            model_name="pluspred",
            name="personalcare_survey",
            field=models.SmallIntegerField(verbose_name="개인정비의 강도"),
        ),
        migrations.AlterField(
            model_name="pluspred",
            name="talk_survey",
            field=models.SmallIntegerField(verbose_name="대화의 강도"),
        ),
        migrations.AlterField(
            model_name="pluspred",
            name="work_survey",
            field=models.SmallIntegerField(verbose_name="당일 업무 유무"),
        ),
    ]
