# Generated by Django 4.1.13 on 2024-06-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0017_alter_pluspred_alcohol_survey_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pluspred",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="일자"),
        ),
        migrations.AlterField(
            model_name="pred",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="일자"),
        ),
    ]
