# Generated by Django 4.1.13 on 2024-06-11 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0018_alter_pluspred_date_alter_pred_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pluspred",
            name="user",
            field=models.ForeignKey(
                max_length=255,
                on_delete=django.db.models.deletion.CASCADE,
                to="survey.pred",
            ),
        ),
    ]
