# Generated by Django 4.1.13 on 2024-06-12 00:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0021_alter_pluspred_user_alter_pred_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="SurveyRoom",
        ),
    ]
