# Generated by Django 4.1.13 on 2024-06-12 00:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0022_delete_message_delete_surveyroom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pred",
            name="user",
        ),
        migrations.DeleteModel(
            name="PlusPred",
        ),
        migrations.DeleteModel(
            name="Pred",
        ),
    ]
