# Generated by Django 4.1.13 on 2024-06-12 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("survey", "0023_remove_pred_user_delete_pluspred_delete_pred"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pred",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_username", models.CharField(max_length=150, verbose_name="유저명")),
                ("predict", models.SmallIntegerField(verbose_name="결과")),
                ("predict_proba", models.SmallIntegerField(verbose_name="잘 잤을 확률")),
                ("sleep_survey", models.SmallIntegerField(verbose_name="숙면여부")),
                ("stress_survey", models.SmallIntegerField(verbose_name="스트레스의 강도")),
                ("positive_survey", models.SmallIntegerField(verbose_name="긍정의 강도")),
                ("date", models.DateField(auto_now_add=True, verbose_name="일자")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlusPred",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_username", models.CharField(max_length=150, verbose_name="유저명")),
                ("date", models.DateField(auto_now_add=True, verbose_name="일자")),
                ("dream_survey", models.SmallIntegerField(verbose_name="꿈의 강도")),
                ("caffeine_survey", models.SmallIntegerField(verbose_name="카페인 강도")),
                ("alcohol_survey", models.SmallIntegerField(verbose_name="알코올의 강도")),
                ("talk_survey", models.SmallIntegerField(verbose_name="대화의 강도")),
                (
                    "personalcare_survey",
                    models.SmallIntegerField(verbose_name="개인정비의 강도"),
                ),
                ("work_survey", models.SmallIntegerField(verbose_name="당일 업무 유무")),
                (
                    "home_survey",
                    models.SmallIntegerField(verbose_name="집에서 많은 시간을 보내는지의 여부"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
