# Generated by Django 4.1.13 on 2024-06-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0024_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pluspred",
            name="date",
            field=models.DateField(verbose_name="일자"),
        ),
        migrations.AlterField(
            model_name="pred",
            name="date",
            field=models.DateField(verbose_name="일자"),
        ),
    ]
